In [1]:
import numpy as np


In [27]:
array = np.array(['A', 'B', 'C'])
   
                  

print(array)
print(array.ndim)
print(array[1:3])

['A' 'B' 'C']
1
['B' 'C']


In [20]:
array = np.array([['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']
   
                  ])

print(array)
print(array.ndim)
print(array[1:3])

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
2
[['D' 'E' 'F']
 ['G' 'H' 'I']]


In [19]:
array = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']]
                  ])

print(array)
print(array.ndim)
print(array[1:3])

[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]]
3
[[['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]]


In [29]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(type(arr))

[1 2 3 4 5]
1
<class 'numpy.ndarray'>


In [33]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2)
print("shape 2*3 matrix:", arr2.shape)
print("dimension", arr2.ndim)

[[1 2 3]
 [4 5 6]]
shape 2*3 matrix: (2, 3)
dimension 2


In [48]:
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.arange(0,11,2))
print(np.linspace(1,2,1))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  2  4  6  8 10]
[1.]


In [50]:
arr3 =np.array(np.arange(0,11,1))
print(arr3)
print(arr3[0])
print(arr3[-1])
print(arr3[1:4])

[ 0  1  2  3  4  5  6  7  8  9 10]
0
10
[1 2 3]


2D Array Slicing




In [61]:
arr = np.array([[10,20,30], 
                [40,50,60]])
print(arr[0,0])
print(arr[1,2])
print(arr[:, 2])
print(arr[1:,])

10
60
[30 60]
[[40 50 60]]


Mathematical Operations

In [63]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("addition:", a+b)
print("substraction:", a-b)
print("multiplication:", a*b)
print("division:", a/b)
print("mean of a:", np.mean(a))
print("mean of b: ", np.mean(b))
print("max of a : ", np.max(a))
print("max of b : ", np.max(b))

addition: [5 7 9]
substraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]
mean of a: 2.0
mean of b:  5.0
max of a :  3
max of b :  6


Reshape and Flatten

In [71]:
arr = np.arange(1,10)

matrix = arr.reshape(3,3)
print("Matrix", matrix)

flat = matrix.flatten()
print("Flattened", flat)

arr2 = np.array([[1,2,3,4],
                 [5,6,7,8]])
print("Matrix 2: ", arr2)
print("Matrix to normal single line", arr2.flatten())

Matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened [1 2 3 4 5 6 7 8 9]
Matrix 2:  [[1 2 3 4]
 [5 6 7 8]]
Matrix to normal single line [1 2 3 4 5 6 7 8]


Random Numbers

In [85]:
print(np.random.rand(2, 3))
print(np.random.randint(1,10, size=(3,1)))

[[0.94881731 0.22618244 0.15226352]
 [0.29556787 0.54011952 0.383058  ]]
[[8]
 [8]
 [1]]
